[package]
name = "nquery"
version = "0.1.0"
authors = ["Aru Sahni <aru.sahni@sparkmeter.io>"]
edition = "2018"

[dependencies]
structopt = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
ureq = { version = "*", features = ["json"] }
env_logger = "0.7"
log = "0.4"
